---
ci:
  autofix_commit_msg: ðŸŽ¨ [pre-commit.ci] Auto format from pre-commit.com hooks
  # Settings for the https://pre-commit.ci/ continuous integration service
  autofix_prs: true
  autoupdate_commit_msg: â¬† [pre-commit.ci] pre-commit autoupdate
  autoupdate_schedule: monthly
# https://pre-commit.com/
# `pre-commit install` to set up the git hook scripts
# `pre-commit autoupdate` to update repos
# `pre-commit run --all-files` run hooks for all file
exclude: (^|/)\..*
repos:
  - hooks:
      - id: check-toml
      - args: ["--unsafe"]
        id: check-yaml
      - id: check-json
      - args: ["--maxkb=51200"]
        id: check-added-large-files
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: destroyed-symlinks
      - id: check-vcs-permalinks
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
  - hooks:
      - args: [--write-changes]
        files: \.(py|sh|rst|yml|yaml|md)$
        id: codespell
    repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
  - hooks:
      - args: [ --fix ]
        id: ruff
      - id: ruff-format
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
